dist: xenial
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
            - lcov
      env:
        - COMPILER="CC=gcc-7 && CXX=g++-7"
        - BUILD_TYPE=Coverage
      install:
        - eval $COMPILER
        - sudo apt-get remove python-enum34
        - sudo pip install --upgrade pip
        - sudo pip install conan
        - conan user
      after_success:
        - lcov --directory . --capture --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' '*/tests/*' '*/.conan/*' --output-file coverage.info
        - lcov --list coverage.info
        - bash <(curl -s https://codecov.io/bash) -f coverage.info;

    - os: osx
      osx_image: xcode10.2
      env:
        - BUILD_TYPE=Debug
      install:
        - brew install conan
        - export -n CC && export -n CXX
        - conan user

script:
  - mkdir out && cd out
  - conan install ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PROJECT_asyop_INCLUDE=out/conan_paths.cmake ..
  - cmake --build . -- -j $(nproc)
  - ctest --output-on-failure
