dist: xenial
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
            - libasio-dev
            - lcov
      env:
        - COMPILER="CC=gcc-7 && CXX=g++-7"
        - BUILD_TYPE=Coverage
      install:
        - eval $COMPILER
      after_success:
        - lcov --directory . --capture --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
        - lcov --list coverage.info
        - bash <(curl -s https://codecov.io/bash) -f coverage.info;

    - os: osx
      osx_image: xcode10.2
      env:
        - BUILD_TYPE=Debug
      install:
        - brew install asio

before_script:
  # Install Catch2
  - git clone --branch v2.5.0 https://github.com/catchorg/Catch2.git
  - mkdir Catch2_build && cd Catch2_build
  - cmake -DBUILD_TESTING=OFF ../Catch2/
  - sudo cmake --build . --target install -- -j $(nproc)
  - cd ..

script:
  - mkdir out && cd out
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build . -- -j $(nproc)
  - ctest --output-on-failure
