dist: trusty
sudo: false

language:
  - cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - libasio-dev

before_script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  # Install Catch2
  - git clone --branch v2.5.0 https://github.com/catchorg/Catch2.git
  - mkdir Catch2_build && cd Catch2_build
  - cmake ../Catch2/
  - sudo make install
  - cd ..

script:
  - mkdir out && cd out
  - cmake ..
  - cmake --build .
  - ctest --output-on-failure
