dist: trusty
sudo: false

language:
  - cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - libasio-dev
      - lcov

before_script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  # Install Catch2
  - git clone --branch v2.5.0 https://github.com/catchorg/Catch2.git
  - mkdir Catch2_build && cd Catch2_build
  - cmake -DBUILD_TESTING=OFF ../Catch2/
  - sudo make install -j $(nproc)
  - cd ..

script:
  - mkdir out && cd out
  - cmake -DCMAKE_BUILD_TYPE=Coverage ..
  - cmake --build . -- -j $(nproc)
  - ctest --output-on-failure

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
  - lcov --list coverage.info
  - if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
        bash <(curl -s https://codecov.io/bash) -f coverage.info;
    fi
